project_id = "aqsagvompemyijkqurku"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-prompt-response]
verify_jwt = false

[functions.score-prompt]
verify_jwt = false